# ai_client.sh
# Abstracting HTTP requests to Large Language Models.

generate_release_notes() {
    local version="$1"
    local type="$2"
    local commit="$3"
    local diff="$4"
    
    local curr_date=$(date +%Y-%m-%d)
    local lang_name="English"
    [ "$RELEASE_LANGUAGE" = "es" ] && lang_name="Spanish"

    local prompt="Act strictly as a Senior Technical Writer. 
CRITICAL: You MUST write the entire response in $lang_name.
Generate release notes for version $version.

## Context
- Project: $PROJECT_NAME
- Primary Author: $AUTHOR_NAME
- Date of Release: $curr_date
- Release Intent (SemVer action): $type

## Contextual Data
Commit Message:
$commit

Code Differences Payload:
$diff

## Requirements Output:
1. Provide valid Markdown format response.
2. Structure sections: 'Executive Summary', 'Detailed Changes', 'Technical Modules Affected'.
3. Extract real meaning out of the code differences payload and explain the 'why'.
4. Do NOT output XML tags like <think>, only the markdown content."

    # Construct JSON payload utilizing Node mapping arguments safely
    # We use export to ensure complex strings (with backticks/newlines) are handled correctly by Node's process.env
    export AI_PROMPT_CONTENT="$prompt"
    export AI_MODEL_NAME="${GROQ_MODEL:-llama-3.3-70b-versatile}"
    
    local payload=$(node -e "
      const data = {
        model: process.env.AI_MODEL_NAME,
        messages: [
            {role: 'system', content: 'You are an expert technical documenter and analyst.'},
            {role: 'user', content: process.env.AI_PROMPT_CONTENT}
        ],
        temperature: 0.2
      };
      console.log(JSON.stringify(data));
    ")
        
    local response=$(curl -sS --max-time 45 "$GROQ_URL" \
        -H "Authorization: Bearer $GROQ_API_KEY" \
        -H "Content-Type: application/json" \
        -d "$payload" || echo "{\"error\": {\"message\": \"Network or Connection Error\"}}")
        
    # Extract content or error message using Node.js for robustness
    export AI_RESPONSE_RAW="$response"
    local content=$(node -e "
      try {
        if (!process.env.AI_RESPONSE_RAW) throw new Error('Empty response');
        const data = JSON.parse(process.env.AI_RESPONSE_RAW);
        if (data.error) {
          process.stderr.write('Groq API Error: ' + (data.error.message || JSON.stringify(data.error)) + '\n');
          process.exit(1);
        }
        if (!data.choices || !data.choices[0]) {
           process.stderr.write('Invalid API Response Structure\n');
           process.exit(1);
        }
        let txt = data.choices[0].message.content || '';
        // Clean thinking tags (multi-line) and redundant whitespace
        txt = txt.replace(/<think>[\s\S]*?<\/think>/g, '').trim();
        process.stdout.write(txt);
      } catch(e) {
        process.stderr.write('AI API Response Parsing Failed\n');
      }
    ")
    
    # If the response was empty or parsing failed
    if [ -z "$content" ]; then
        echo "Warning: AI Generation failed. Using fallback template." >&2
        printf "# Release v%s\n\n> ⚠️ **AI Generation Warning:** The professional notes could not be generated automatically. Deep analysis is missing.\n\n## Executive Summary\n- Intent: **%s**\n- Core Change: **%s**\n\n## Detailed Changes\nRefer to the commit history for more details on the following message:\n\`%s\`\n\n---\n*Generated by SemVer AI Tool (Fallback Mode)*\n" "$version" "$type" "$commit" "$commit"
        return 0
    fi
    
    echo "$content"
}
