# ai_client.sh
# Abstracting HTTP requests to Large Language Models.

generate_release_notes() {
    local version="$1"
    local type="$2"
    local commit="$3"
    local diff="$4"
    
    local curr_date=$(date +%Y-%m-%d)
    
    local prompt="Act strictly as a Senior Technical Writer for a software engineering team.
Generate release notes for version $version.

## Context
- Project: $PROJECT_NAME
- Primary Author: $AUTHOR_NAME
- Date of Release: $curr_date
- Release Intent (SemVer action): $type

## Contextual Data
Commit Message:
$commit

Code Differences Payload:
$diff

## Requirements Output:
1. Provide valid Markdown format response.
2. Structure sections: 'Executive Summary', 'Detailed Changes', 'Technical Modules Affected'.
3. Extract real meaning out of the code differences payload and explain the 'why'.
4. Do NOT output XML tags like <think>, only the markdown content."

    # Construct JSON payload utilizing Node mapping arguments safely
    local payload=$(PROMPT="$prompt" node -e "
      console.log(JSON.stringify({
        model: process.env.GROQ_MODEL || 'llama-3.1-70b-versatile',
        messages: [
            {role: 'system', content: 'You are an expert technical documenter and analyst.'},
            {role: 'user', content: process.env.PROMPT}
        ],
        temperature: 0.2
      }));
    ")
        
    local response=$(curl -sS --max-time 45 "$GROQ_URL" \
        -H "Authorization: Bearer $GROQ_API_KEY" \
        -H "Content-Type: application/json" \
        -d "$payload" || echo "{\"error\": {\"message\": \"Network or Curl Error\"}}")
        
    # Extract content or error message using Node.js for robustness
    export AI_RESPONSE_RAW="$response"
    local content=$(node -e "
      try {
        const data = JSON.parse(process.env.AI_RESPONSE_RAW);
        if (data.error) {
          process.stderr.write('Groq API Error: ' + (data.error.message || 'Unknown error') + '\n');
          process.exit(0);
        }
        let txt = data.choices[0].message.content || '';
        // Clean thinking tags (multi-line)
        txt = txt.replace(/<think>[\s\S]*?<\/think>/g, '');
        process.stdout.write(txt.trim());
      } catch(e) {
        process.stderr.write('AI API Response Parsing Failed\n');
      }
    ")
    
    # If the response was empty or parsing failed
    if [ -z "$content" ]; then
        echo "Warning: AI Generation failed. Using fallback template." >&2
        printf "# Release v%s\n\n> ⚠️ **AI Generation Warning:** The professional notes could not be generated automatically. Deep analysis is missing.\n\n## Executive Summary\n- Intent: **%s**\n- Core Change: **%s**\n\n## Detailed Changes\nRefer to the commit history for more details on the following message:\n\`%s\`\n\n---\n*Generated by SemVer AI Tool (Fallback Mode)*\n" "$version" "$type" "$commit" "$commit"
        return 0
    fi
    
    echo "$content"
}
